version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: archivedgames
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data

  app:
    image: alpine:3.20
    command: ["sh","-c","echo 'backend agent will replace this service' && sleep 3600"]
    env_file:
      - .env
      - .env.local
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio

volumes:
  pgdata:
  miniodata:
