// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/file"
	"github.com/deicod/archivedgames/ent/game"
)

// FileCreate is the builder for creating a File entity.
type FileCreate struct {
	config
	mutation *FileMutation
	hooks    []Hook
}

// SetPath sets the "path" field.
func (_c *FileCreate) SetPath(v string) *FileCreate {
	_c.mutation.SetPath(v)
	return _c
}

// SetOriginalName sets the "original_name" field.
func (_c *FileCreate) SetOriginalName(v string) *FileCreate {
	_c.mutation.SetOriginalName(v)
	return _c
}

// SetNormalizedName sets the "normalized_name" field.
func (_c *FileCreate) SetNormalizedName(v string) *FileCreate {
	_c.mutation.SetNormalizedName(v)
	return _c
}

// SetSetKey sets the "set_key" field.
func (_c *FileCreate) SetSetKey(v string) *FileCreate {
	_c.mutation.SetSetKey(v)
	return _c
}

// SetNillableSetKey sets the "set_key" field if the given value is not nil.
func (_c *FileCreate) SetNillableSetKey(v *string) *FileCreate {
	if v != nil {
		_c.SetSetKey(*v)
	}
	return _c
}

// SetChecksum sets the "checksum" field.
func (_c *FileCreate) SetChecksum(v string) *FileCreate {
	_c.mutation.SetChecksum(v)
	return _c
}

// SetSizeBytes sets the "size_bytes" field.
func (_c *FileCreate) SetSizeBytes(v int64) *FileCreate {
	_c.mutation.SetSizeBytes(v)
	return _c
}

// SetMimeType sets the "mime_type" field.
func (_c *FileCreate) SetMimeType(v string) *FileCreate {
	_c.mutation.SetMimeType(v)
	return _c
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_c *FileCreate) SetNillableMimeType(v *string) *FileCreate {
	if v != nil {
		_c.SetMimeType(*v)
	}
	return _c
}

// SetFormat sets the "format" field.
func (_c *FileCreate) SetFormat(v string) *FileCreate {
	_c.mutation.SetFormat(v)
	return _c
}

// SetNillableFormat sets the "format" field if the given value is not nil.
func (_c *FileCreate) SetNillableFormat(v *string) *FileCreate {
	if v != nil {
		_c.SetFormat(*v)
	}
	return _c
}

// SetSource sets the "source" field.
func (_c *FileCreate) SetSource(v string) *FileCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetQuarantine sets the "quarantine" field.
func (_c *FileCreate) SetQuarantine(v bool) *FileCreate {
	_c.mutation.SetQuarantine(v)
	return _c
}

// SetNillableQuarantine sets the "quarantine" field if the given value is not nil.
func (_c *FileCreate) SetNillableQuarantine(v *bool) *FileCreate {
	if v != nil {
		_c.SetQuarantine(*v)
	}
	return _c
}

// SetNeedsReview sets the "needs_review" field.
func (_c *FileCreate) SetNeedsReview(v bool) *FileCreate {
	_c.mutation.SetNeedsReview(v)
	return _c
}

// SetNillableNeedsReview sets the "needs_review" field if the given value is not nil.
func (_c *FileCreate) SetNillableNeedsReview(v *bool) *FileCreate {
	if v != nil {
		_c.SetNeedsReview(*v)
	}
	return _c
}

// SetDiskNumber sets the "disk_number" field.
func (_c *FileCreate) SetDiskNumber(v int) *FileCreate {
	_c.mutation.SetDiskNumber(v)
	return _c
}

// SetNillableDiskNumber sets the "disk_number" field if the given value is not nil.
func (_c *FileCreate) SetNillableDiskNumber(v *int) *FileCreate {
	if v != nil {
		_c.SetDiskNumber(*v)
	}
	return _c
}

// SetSide sets the "side" field.
func (_c *FileCreate) SetSide(v string) *FileCreate {
	_c.mutation.SetSide(v)
	return _c
}

// SetNillableSide sets the "side" field if the given value is not nil.
func (_c *FileCreate) SetNillableSide(v *string) *FileCreate {
	if v != nil {
		_c.SetSide(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *FileCreate) SetID(v string) *FileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FileCreate) SetNillableID(v *string) *FileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_c *FileCreate) SetGameID(id string) *FileCreate {
	_c.mutation.SetGameID(id)
	return _c
}

// SetGame sets the "game" edge to the Game entity.
func (_c *FileCreate) SetGame(v *Game) *FileCreate {
	return _c.SetGameID(v.ID)
}

// Mutation returns the FileMutation object of the builder.
func (_c *FileCreate) Mutation() *FileMutation {
	return _c.mutation
}

// Save creates the File in the database.
func (_c *FileCreate) Save(ctx context.Context) (*File, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileCreate) SaveX(ctx context.Context) *File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileCreate) defaults() {
	if _, ok := _c.mutation.Quarantine(); !ok {
		v := file.DefaultQuarantine
		_c.mutation.SetQuarantine(v)
	}
	if _, ok := _c.mutation.NeedsReview(); !ok {
		v := file.DefaultNeedsReview
		_c.mutation.SetNeedsReview(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := file.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileCreate) check() error {
	if _, ok := _c.mutation.Path(); !ok {
		return &ValidationError{Name: "path", err: errors.New(`ent: missing required field "File.path"`)}
	}
	if _, ok := _c.mutation.OriginalName(); !ok {
		return &ValidationError{Name: "original_name", err: errors.New(`ent: missing required field "File.original_name"`)}
	}
	if _, ok := _c.mutation.NormalizedName(); !ok {
		return &ValidationError{Name: "normalized_name", err: errors.New(`ent: missing required field "File.normalized_name"`)}
	}
	if _, ok := _c.mutation.Checksum(); !ok {
		return &ValidationError{Name: "checksum", err: errors.New(`ent: missing required field "File.checksum"`)}
	}
	if _, ok := _c.mutation.SizeBytes(); !ok {
		return &ValidationError{Name: "size_bytes", err: errors.New(`ent: missing required field "File.size_bytes"`)}
	}
	if _, ok := _c.mutation.Source(); !ok {
		return &ValidationError{Name: "source", err: errors.New(`ent: missing required field "File.source"`)}
	}
	if _, ok := _c.mutation.Quarantine(); !ok {
		return &ValidationError{Name: "quarantine", err: errors.New(`ent: missing required field "File.quarantine"`)}
	}
	if _, ok := _c.mutation.NeedsReview(); !ok {
		return &ValidationError{Name: "needs_review", err: errors.New(`ent: missing required field "File.needs_review"`)}
	}
	if len(_c.mutation.GameIDs()) == 0 {
		return &ValidationError{Name: "game", err: errors.New(`ent: missing required edge "File.game"`)}
	}
	return nil
}

func (_c *FileCreate) sqlSave(ctx context.Context) (*File, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected File.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileCreate) createSpec() (*File, *sqlgraph.CreateSpec) {
	var (
		_node = &File{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(file.Table, sqlgraph.NewFieldSpec(file.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Path(); ok {
		_spec.SetField(file.FieldPath, field.TypeString, value)
		_node.Path = value
	}
	if value, ok := _c.mutation.OriginalName(); ok {
		_spec.SetField(file.FieldOriginalName, field.TypeString, value)
		_node.OriginalName = value
	}
	if value, ok := _c.mutation.NormalizedName(); ok {
		_spec.SetField(file.FieldNormalizedName, field.TypeString, value)
		_node.NormalizedName = value
	}
	if value, ok := _c.mutation.SetKey(); ok {
		_spec.SetField(file.FieldSetKey, field.TypeString, value)
		_node.SetKey = value
	}
	if value, ok := _c.mutation.Checksum(); ok {
		_spec.SetField(file.FieldChecksum, field.TypeString, value)
		_node.Checksum = value
	}
	if value, ok := _c.mutation.SizeBytes(); ok {
		_spec.SetField(file.FieldSizeBytes, field.TypeInt64, value)
		_node.SizeBytes = value
	}
	if value, ok := _c.mutation.MimeType(); ok {
		_spec.SetField(file.FieldMimeType, field.TypeString, value)
		_node.MimeType = value
	}
	if value, ok := _c.mutation.Format(); ok {
		_spec.SetField(file.FieldFormat, field.TypeString, value)
		_node.Format = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(file.FieldSource, field.TypeString, value)
		_node.Source = value
	}
	if value, ok := _c.mutation.Quarantine(); ok {
		_spec.SetField(file.FieldQuarantine, field.TypeBool, value)
		_node.Quarantine = value
	}
	if value, ok := _c.mutation.NeedsReview(); ok {
		_spec.SetField(file.FieldNeedsReview, field.TypeBool, value)
		_node.NeedsReview = value
	}
	if value, ok := _c.mutation.DiskNumber(); ok {
		_spec.SetField(file.FieldDiskNumber, field.TypeInt, value)
		_node.DiskNumber = &value
	}
	if value, ok := _c.mutation.Side(); ok {
		_spec.SetField(file.FieldSide, field.TypeString, value)
		_node.Side = value
	}
	if nodes := _c.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   file.GameTable,
			Columns: []string{file.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.game_files = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileCreateBulk is the builder for creating many File entities in bulk.
type FileCreateBulk struct {
	config
	err      error
	builders []*FileCreate
}

// Save creates the File entities in the database.
func (_c *FileCreateBulk) Save(ctx context.Context) ([]*File, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*File, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileCreateBulk) SaveX(ctx context.Context) []*File {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
