// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/file"
	"github.com/deicod/archivedgames/ent/filereaction"
)

// FileReactionCreate is the builder for creating a FileReaction entity.
type FileReactionCreate struct {
	config
	mutation *FileReactionMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *FileReactionCreate) SetUserID(v string) *FileReactionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *FileReactionCreate) SetValue(v int) *FileReactionCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetID sets the "id" field.
func (_c *FileReactionCreate) SetID(v string) *FileReactionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *FileReactionCreate) SetNillableID(v *string) *FileReactionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetFileID sets the "file" edge to the File entity by ID.
func (_c *FileReactionCreate) SetFileID(id string) *FileReactionCreate {
	_c.mutation.SetFileID(id)
	return _c
}

// SetFile sets the "file" edge to the File entity.
func (_c *FileReactionCreate) SetFile(v *File) *FileReactionCreate {
	return _c.SetFileID(v.ID)
}

// Mutation returns the FileReactionMutation object of the builder.
func (_c *FileReactionCreate) Mutation() *FileReactionMutation {
	return _c.mutation
}

// Save creates the FileReaction in the database.
func (_c *FileReactionCreate) Save(ctx context.Context) (*FileReaction, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *FileReactionCreate) SaveX(ctx context.Context) *FileReaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileReactionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileReactionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *FileReactionCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := filereaction.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *FileReactionCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "FileReaction.user_id"`)}
	}
	if _, ok := _c.mutation.Value(); !ok {
		return &ValidationError{Name: "value", err: errors.New(`ent: missing required field "FileReaction.value"`)}
	}
	if len(_c.mutation.FileIDs()) == 0 {
		return &ValidationError{Name: "file", err: errors.New(`ent: missing required edge "FileReaction.file"`)}
	}
	return nil
}

func (_c *FileReactionCreate) sqlSave(ctx context.Context) (*FileReaction, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected FileReaction.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *FileReactionCreate) createSpec() (*FileReaction, *sqlgraph.CreateSpec) {
	var (
		_node = &FileReaction{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(filereaction.Table, sqlgraph.NewFieldSpec(filereaction.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(filereaction.FieldUserID, field.TypeString, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(filereaction.FieldValue, field.TypeInt, value)
		_node.Value = value
	}
	if nodes := _c.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   filereaction.FileTable,
			Columns: []string{filereaction.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.file_reaction_file = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FileReactionCreateBulk is the builder for creating many FileReaction entities in bulk.
type FileReactionCreateBulk struct {
	config
	err      error
	builders []*FileReactionCreate
}

// Save creates the FileReaction entities in the database.
func (_c *FileReactionCreateBulk) Save(ctx context.Context) ([]*FileReaction, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*FileReaction, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FileReactionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *FileReactionCreateBulk) SaveX(ctx context.Context) []*FileReaction {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *FileReactionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *FileReactionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
