// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/deicod/archivedgames/ent/game"
)

// Game is the model entity for the Game schema.
type Game struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform game.Platform `json:"platform,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Year holds the value of the "year" field.
	Year *int `json:"year,omitempty"`
	// Publisher holds the value of the "publisher" field.
	Publisher string `json:"publisher,omitempty"`
	// Developer holds the value of the "developer" field.
	Developer string `json:"developer,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GameQuery when eager-loading is set.
	Edges        GameEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GameEdges holds the relations/edges for other nodes in the graph.
type GameEdges struct {
	// Files holds the value of the files edge.
	Files []*File `json:"files,omitempty"`
	// Images holds the value of the images edge.
	Images []*Image `json:"images,omitempty"`
	// Comments holds the value of the comments edge.
	Comments []*Comment `json:"comments,omitempty"`
	// Groups holds the value of the groups edge.
	Groups []*FileGroup `json:"groups,omitempty"`
	// Likes holds the value of the likes edge.
	Likes []*GameLike `json:"likes,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
	// totalCount holds the count of the edges above.
	totalCount [5]map[string]int

	namedFiles    map[string][]*File
	namedImages   map[string][]*Image
	namedComments map[string][]*Comment
	namedGroups   map[string][]*FileGroup
	namedLikes    map[string][]*GameLike
}

// FilesOrErr returns the Files value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) FilesOrErr() ([]*File, error) {
	if e.loadedTypes[0] {
		return e.Files, nil
	}
	return nil, &NotLoadedError{edge: "files"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) ImagesOrErr() ([]*Image, error) {
	if e.loadedTypes[1] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// CommentsOrErr returns the Comments value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) CommentsOrErr() ([]*Comment, error) {
	if e.loadedTypes[2] {
		return e.Comments, nil
	}
	return nil, &NotLoadedError{edge: "comments"}
}

// GroupsOrErr returns the Groups value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) GroupsOrErr() ([]*FileGroup, error) {
	if e.loadedTypes[3] {
		return e.Groups, nil
	}
	return nil, &NotLoadedError{edge: "groups"}
}

// LikesOrErr returns the Likes value or an error if the edge
// was not loaded in eager-loading.
func (e GameEdges) LikesOrErr() ([]*GameLike, error) {
	if e.loadedTypes[4] {
		return e.Likes, nil
	}
	return nil, &NotLoadedError{edge: "likes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Game) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case game.FieldYear:
			values[i] = new(sql.NullInt64)
		case game.FieldID, game.FieldSlug, game.FieldPlatform, game.FieldTitle, game.FieldPublisher, game.FieldDeveloper:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Game fields.
func (_m *Game) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case game.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case game.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case game.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				_m.Platform = game.Platform(value.String)
			}
		case game.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case game.FieldYear:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field year", values[i])
			} else if value.Valid {
				_m.Year = new(int)
				*_m.Year = int(value.Int64)
			}
		case game.FieldPublisher:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field publisher", values[i])
			} else if value.Valid {
				_m.Publisher = value.String
			}
		case game.FieldDeveloper:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field developer", values[i])
			} else if value.Valid {
				_m.Developer = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Game.
// This includes values selected through modifiers, order, etc.
func (_m *Game) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFiles queries the "files" edge of the Game entity.
func (_m *Game) QueryFiles() *FileQuery {
	return NewGameClient(_m.config).QueryFiles(_m)
}

// QueryImages queries the "images" edge of the Game entity.
func (_m *Game) QueryImages() *ImageQuery {
	return NewGameClient(_m.config).QueryImages(_m)
}

// QueryComments queries the "comments" edge of the Game entity.
func (_m *Game) QueryComments() *CommentQuery {
	return NewGameClient(_m.config).QueryComments(_m)
}

// QueryGroups queries the "groups" edge of the Game entity.
func (_m *Game) QueryGroups() *FileGroupQuery {
	return NewGameClient(_m.config).QueryGroups(_m)
}

// QueryLikes queries the "likes" edge of the Game entity.
func (_m *Game) QueryLikes() *GameLikeQuery {
	return NewGameClient(_m.config).QueryLikes(_m)
}

// Update returns a builder for updating this Game.
// Note that you need to call Game.Unwrap() before calling this method if this Game
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Game) Update() *GameUpdateOne {
	return NewGameClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Game entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Game) Unwrap() *Game {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Game is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Game) String() string {
	var builder strings.Builder
	builder.WriteString("Game(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(fmt.Sprintf("%v", _m.Platform))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	if v := _m.Year; v != nil {
		builder.WriteString("year=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("publisher=")
	builder.WriteString(_m.Publisher)
	builder.WriteString(", ")
	builder.WriteString("developer=")
	builder.WriteString(_m.Developer)
	builder.WriteByte(')')
	return builder.String()
}

// NamedFiles returns the Files named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Game) NamedFiles(name string) ([]*File, error) {
	if _m.Edges.namedFiles == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedFiles[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Game) appendNamedFiles(name string, edges ...*File) {
	if _m.Edges.namedFiles == nil {
		_m.Edges.namedFiles = make(map[string][]*File)
	}
	if len(edges) == 0 {
		_m.Edges.namedFiles[name] = []*File{}
	} else {
		_m.Edges.namedFiles[name] = append(_m.Edges.namedFiles[name], edges...)
	}
}

// NamedImages returns the Images named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Game) NamedImages(name string) ([]*Image, error) {
	if _m.Edges.namedImages == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedImages[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Game) appendNamedImages(name string, edges ...*Image) {
	if _m.Edges.namedImages == nil {
		_m.Edges.namedImages = make(map[string][]*Image)
	}
	if len(edges) == 0 {
		_m.Edges.namedImages[name] = []*Image{}
	} else {
		_m.Edges.namedImages[name] = append(_m.Edges.namedImages[name], edges...)
	}
}

// NamedComments returns the Comments named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Game) NamedComments(name string) ([]*Comment, error) {
	if _m.Edges.namedComments == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedComments[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Game) appendNamedComments(name string, edges ...*Comment) {
	if _m.Edges.namedComments == nil {
		_m.Edges.namedComments = make(map[string][]*Comment)
	}
	if len(edges) == 0 {
		_m.Edges.namedComments[name] = []*Comment{}
	} else {
		_m.Edges.namedComments[name] = append(_m.Edges.namedComments[name], edges...)
	}
}

// NamedGroups returns the Groups named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Game) NamedGroups(name string) ([]*FileGroup, error) {
	if _m.Edges.namedGroups == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedGroups[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Game) appendNamedGroups(name string, edges ...*FileGroup) {
	if _m.Edges.namedGroups == nil {
		_m.Edges.namedGroups = make(map[string][]*FileGroup)
	}
	if len(edges) == 0 {
		_m.Edges.namedGroups[name] = []*FileGroup{}
	} else {
		_m.Edges.namedGroups[name] = append(_m.Edges.namedGroups[name], edges...)
	}
}

// NamedLikes returns the Likes named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Game) NamedLikes(name string) ([]*GameLike, error) {
	if _m.Edges.namedLikes == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedLikes[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Game) appendNamedLikes(name string, edges ...*GameLike) {
	if _m.Edges.namedLikes == nil {
		_m.Edges.namedLikes = make(map[string][]*GameLike)
	}
	if len(edges) == 0 {
		_m.Edges.namedLikes[name] = []*GameLike{}
	} else {
		_m.Edges.namedLikes[name] = append(_m.Edges.namedLikes[name], edges...)
	}
}

// Games is a parsable slice of Game.
type Games []*Game
