// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/game"
	"github.com/deicod/archivedgames/ent/gamelike"
	"github.com/deicod/archivedgames/ent/predicate"
)

// GameLikeUpdate is the builder for updating GameLike entities.
type GameLikeUpdate struct {
	config
	hooks    []Hook
	mutation *GameLikeMutation
}

// Where appends a list predicates to the GameLikeUpdate builder.
func (_u *GameLikeUpdate) Where(ps ...predicate.GameLike) *GameLikeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *GameLikeUpdate) SetUserID(v string) *GameLikeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GameLikeUpdate) SetNillableUserID(v *string) *GameLikeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_u *GameLikeUpdate) SetGameID(id string) *GameLikeUpdate {
	_u.mutation.SetGameID(id)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *GameLikeUpdate) SetGame(v *Game) *GameLikeUpdate {
	return _u.SetGameID(v.ID)
}

// Mutation returns the GameLikeMutation object of the builder.
func (_u *GameLikeUpdate) Mutation() *GameLikeMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *GameLikeUpdate) ClearGame() *GameLikeUpdate {
	_u.mutation.ClearGame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *GameLikeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameLikeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *GameLikeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameLikeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameLikeUpdate) check() error {
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GameLike.game"`)
	}
	return nil
}

func (_u *GameLikeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gamelike.Table, gamelike.Columns, sqlgraph.NewFieldSpec(gamelike.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(gamelike.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   gamelike.GameTable,
			Columns: []string{gamelike.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   gamelike.GameTable,
			Columns: []string{gamelike.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamelike.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// GameLikeUpdateOne is the builder for updating a single GameLike entity.
type GameLikeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *GameLikeMutation
}

// SetUserID sets the "user_id" field.
func (_u *GameLikeUpdateOne) SetUserID(v string) *GameLikeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *GameLikeUpdateOne) SetNillableUserID(v *string) *GameLikeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_u *GameLikeUpdateOne) SetGameID(id string) *GameLikeUpdateOne {
	_u.mutation.SetGameID(id)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *GameLikeUpdateOne) SetGame(v *Game) *GameLikeUpdateOne {
	return _u.SetGameID(v.ID)
}

// Mutation returns the GameLikeMutation object of the builder.
func (_u *GameLikeUpdateOne) Mutation() *GameLikeMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *GameLikeUpdateOne) ClearGame() *GameLikeUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// Where appends a list predicates to the GameLikeUpdate builder.
func (_u *GameLikeUpdateOne) Where(ps ...predicate.GameLike) *GameLikeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *GameLikeUpdateOne) Select(field string, fields ...string) *GameLikeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated GameLike entity.
func (_u *GameLikeUpdateOne) Save(ctx context.Context) (*GameLike, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *GameLikeUpdateOne) SaveX(ctx context.Context) *GameLike {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *GameLikeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *GameLikeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *GameLikeUpdateOne) check() error {
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "GameLike.game"`)
	}
	return nil
}

func (_u *GameLikeUpdateOne) sqlSave(ctx context.Context) (_node *GameLike, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(gamelike.Table, gamelike.Columns, sqlgraph.NewFieldSpec(gamelike.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "GameLike.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, gamelike.FieldID)
		for _, f := range fields {
			if !gamelike.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != gamelike.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(gamelike.FieldUserID, field.TypeString, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   gamelike.GameTable,
			Columns: []string{gamelike.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   gamelike.GameTable,
			Columns: []string{gamelike.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &GameLike{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{gamelike.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
