// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/game"
	"github.com/deicod/archivedgames/ent/image"
	"github.com/deicod/archivedgames/ent/predicate"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (iu *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	iu.mutation.Where(ps...)
	return iu
}

// SetKind sets the "kind" field.
func (iu *ImageUpdate) SetKind(i image.Kind) *ImageUpdate {
	iu.mutation.SetKind(i)
	return iu
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableKind(i *image.Kind) *ImageUpdate {
	if i != nil {
		iu.SetKind(*i)
	}
	return iu
}

// SetPosition sets the "position" field.
func (iu *ImageUpdate) SetPosition(i int) *ImageUpdate {
	iu.mutation.ResetPosition()
	iu.mutation.SetPosition(i)
	return iu
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (iu *ImageUpdate) SetNillablePosition(i *int) *ImageUpdate {
	if i != nil {
		iu.SetPosition(*i)
	}
	return iu
}

// AddPosition adds i to the "position" field.
func (iu *ImageUpdate) AddPosition(i int) *ImageUpdate {
	iu.mutation.AddPosition(i)
	return iu
}

// SetS3Key sets the "s3_key" field.
func (iu *ImageUpdate) SetS3Key(s string) *ImageUpdate {
	iu.mutation.SetS3Key(s)
	return iu
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableS3Key(s *string) *ImageUpdate {
	if s != nil {
		iu.SetS3Key(*s)
	}
	return iu
}

// SetWidth sets the "width" field.
func (iu *ImageUpdate) SetWidth(i int) *ImageUpdate {
	iu.mutation.ResetWidth()
	iu.mutation.SetWidth(i)
	return iu
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableWidth(i *int) *ImageUpdate {
	if i != nil {
		iu.SetWidth(*i)
	}
	return iu
}

// AddWidth adds i to the "width" field.
func (iu *ImageUpdate) AddWidth(i int) *ImageUpdate {
	iu.mutation.AddWidth(i)
	return iu
}

// SetHeight sets the "height" field.
func (iu *ImageUpdate) SetHeight(i int) *ImageUpdate {
	iu.mutation.ResetHeight()
	iu.mutation.SetHeight(i)
	return iu
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (iu *ImageUpdate) SetNillableHeight(i *int) *ImageUpdate {
	if i != nil {
		iu.SetHeight(*i)
	}
	return iu
}

// AddHeight adds i to the "height" field.
func (iu *ImageUpdate) AddHeight(i int) *ImageUpdate {
	iu.mutation.AddHeight(i)
	return iu
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (iu *ImageUpdate) SetGameID(id string) *ImageUpdate {
	iu.mutation.SetGameID(id)
	return iu
}

// SetGame sets the "game" edge to the Game entity.
func (iu *ImageUpdate) SetGame(g *Game) *ImageUpdate {
	return iu.SetGameID(g.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (iu *ImageUpdate) Mutation() *ImageMutation {
	return iu.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (iu *ImageUpdate) ClearGame() *ImageUpdate {
	iu.mutation.ClearGame()
	return iu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (iu *ImageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, iu.sqlSave, iu.mutation, iu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iu *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := iu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (iu *ImageUpdate) Exec(ctx context.Context) error {
	_, err := iu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iu *ImageUpdate) ExecX(ctx context.Context) {
	if err := iu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iu *ImageUpdate) check() error {
	if v, ok := iu.mutation.Kind(); ok {
		if err := image.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Image.kind": %w`, err)}
		}
	}
	if iu.mutation.GameCleared() && len(iu.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Image.game"`)
	}
	return nil
}

func (iu *ImageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := iu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeString))
	if ps := iu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iu.mutation.Kind(); ok {
		_spec.SetField(image.FieldKind, field.TypeEnum, value)
	}
	if value, ok := iu.mutation.Position(); ok {
		_spec.SetField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := iu.mutation.AddedPosition(); ok {
		_spec.AddField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := iu.mutation.S3Key(); ok {
		_spec.SetField(image.FieldS3Key, field.TypeString, value)
	}
	if value, ok := iu.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := iu.mutation.AddedWidth(); ok {
		_spec.AddField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := iu.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := iu.mutation.AddedHeight(); ok {
		_spec.AddField(image.FieldHeight, field.TypeInt, value)
	}
	if iu.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iu.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, iu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	iu.mutation.done = true
	return n, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetKind sets the "kind" field.
func (iuo *ImageUpdateOne) SetKind(i image.Kind) *ImageUpdateOne {
	iuo.mutation.SetKind(i)
	return iuo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableKind(i *image.Kind) *ImageUpdateOne {
	if i != nil {
		iuo.SetKind(*i)
	}
	return iuo
}

// SetPosition sets the "position" field.
func (iuo *ImageUpdateOne) SetPosition(i int) *ImageUpdateOne {
	iuo.mutation.ResetPosition()
	iuo.mutation.SetPosition(i)
	return iuo
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillablePosition(i *int) *ImageUpdateOne {
	if i != nil {
		iuo.SetPosition(*i)
	}
	return iuo
}

// AddPosition adds i to the "position" field.
func (iuo *ImageUpdateOne) AddPosition(i int) *ImageUpdateOne {
	iuo.mutation.AddPosition(i)
	return iuo
}

// SetS3Key sets the "s3_key" field.
func (iuo *ImageUpdateOne) SetS3Key(s string) *ImageUpdateOne {
	iuo.mutation.SetS3Key(s)
	return iuo
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableS3Key(s *string) *ImageUpdateOne {
	if s != nil {
		iuo.SetS3Key(*s)
	}
	return iuo
}

// SetWidth sets the "width" field.
func (iuo *ImageUpdateOne) SetWidth(i int) *ImageUpdateOne {
	iuo.mutation.ResetWidth()
	iuo.mutation.SetWidth(i)
	return iuo
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableWidth(i *int) *ImageUpdateOne {
	if i != nil {
		iuo.SetWidth(*i)
	}
	return iuo
}

// AddWidth adds i to the "width" field.
func (iuo *ImageUpdateOne) AddWidth(i int) *ImageUpdateOne {
	iuo.mutation.AddWidth(i)
	return iuo
}

// SetHeight sets the "height" field.
func (iuo *ImageUpdateOne) SetHeight(i int) *ImageUpdateOne {
	iuo.mutation.ResetHeight()
	iuo.mutation.SetHeight(i)
	return iuo
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (iuo *ImageUpdateOne) SetNillableHeight(i *int) *ImageUpdateOne {
	if i != nil {
		iuo.SetHeight(*i)
	}
	return iuo
}

// AddHeight adds i to the "height" field.
func (iuo *ImageUpdateOne) AddHeight(i int) *ImageUpdateOne {
	iuo.mutation.AddHeight(i)
	return iuo
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (iuo *ImageUpdateOne) SetGameID(id string) *ImageUpdateOne {
	iuo.mutation.SetGameID(id)
	return iuo
}

// SetGame sets the "game" edge to the Game entity.
func (iuo *ImageUpdateOne) SetGame(g *Game) *ImageUpdateOne {
	return iuo.SetGameID(g.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (iuo *ImageUpdateOne) Mutation() *ImageMutation {
	return iuo.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (iuo *ImageUpdateOne) ClearGame() *ImageUpdateOne {
	iuo.mutation.ClearGame()
	return iuo
}

// Where appends a list predicates to the ImageUpdate builder.
func (iuo *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	iuo.mutation.Where(ps...)
	return iuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (iuo *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	iuo.fields = append([]string{field}, fields...)
	return iuo
}

// Save executes the query and returns the updated Image entity.
func (iuo *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	return withHooks(ctx, iuo.sqlSave, iuo.mutation, iuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (iuo *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := iuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (iuo *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := iuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (iuo *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := iuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (iuo *ImageUpdateOne) check() error {
	if v, ok := iuo.mutation.Kind(); ok {
		if err := image.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Image.kind": %w`, err)}
		}
	}
	if iuo.mutation.GameCleared() && len(iuo.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Image.game"`)
	}
	return nil
}

func (iuo *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	if err := iuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeString))
	id, ok := iuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := iuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := iuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := iuo.mutation.Kind(); ok {
		_spec.SetField(image.FieldKind, field.TypeEnum, value)
	}
	if value, ok := iuo.mutation.Position(); ok {
		_spec.SetField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.AddedPosition(); ok {
		_spec.AddField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.S3Key(); ok {
		_spec.SetField(image.FieldS3Key, field.TypeString, value)
	}
	if value, ok := iuo.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.AddedWidth(); ok {
		_spec.AddField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := iuo.mutation.AddedHeight(); ok {
		_spec.AddField(image.FieldHeight, field.TypeInt, value)
	}
	if iuo.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := iuo.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Image{config: iuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, iuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	iuo.mutation.done = true
	return _node, nil
}
