// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/game"
	"github.com/deicod/archivedgames/ent/image"
	"github.com/deicod/archivedgames/ent/predicate"
)

// ImageUpdate is the builder for updating Image entities.
type ImageUpdate struct {
	config
	hooks    []Hook
	mutation *ImageMutation
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdate) Where(ps ...predicate.Image) *ImageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetKind sets the "kind" field.
func (_u *ImageUpdate) SetKind(v image.Kind) *ImageUpdate {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableKind(v *image.Kind) *ImageUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *ImageUpdate) SetPosition(v int) *ImageUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ImageUpdate) SetNillablePosition(v *int) *ImageUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *ImageUpdate) AddPosition(v int) *ImageUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *ImageUpdate) SetS3Key(v string) *ImageUpdate {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableS3Key(v *string) *ImageUpdate {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageUpdate) SetWidth(v int) *ImageUpdate {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableWidth(v *int) *ImageUpdate {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageUpdate) AddWidth(v int) *ImageUpdate {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageUpdate) SetHeight(v int) *ImageUpdate {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageUpdate) SetNillableHeight(v *int) *ImageUpdate {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageUpdate) AddHeight(v int) *ImageUpdate {
	_u.mutation.AddHeight(v)
	return _u
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_u *ImageUpdate) SetGameID(id string) *ImageUpdate {
	_u.mutation.SetGameID(id)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *ImageUpdate) SetGame(v *Game) *ImageUpdate {
	return _u.SetGameID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdate) Mutation() *ImageMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *ImageUpdate) ClearGame() *ImageUpdate {
	_u.mutation.ClearGame()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ImageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ImageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageUpdate) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := image.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Image.kind": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Image.game"`)
	}
	return nil
}

func (_u *ImageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(image.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(image.FieldS3Key, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(image.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ImageUpdateOne is the builder for updating a single Image entity.
type ImageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ImageMutation
}

// SetKind sets the "kind" field.
func (_u *ImageUpdateOne) SetKind(v image.Kind) *ImageUpdateOne {
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableKind(v *image.Kind) *ImageUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *ImageUpdateOne) SetPosition(v int) *ImageUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillablePosition(v *int) *ImageUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *ImageUpdateOne) AddPosition(v int) *ImageUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetS3Key sets the "s3_key" field.
func (_u *ImageUpdateOne) SetS3Key(v string) *ImageUpdateOne {
	_u.mutation.SetS3Key(v)
	return _u
}

// SetNillableS3Key sets the "s3_key" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableS3Key(v *string) *ImageUpdateOne {
	if v != nil {
		_u.SetS3Key(*v)
	}
	return _u
}

// SetWidth sets the "width" field.
func (_u *ImageUpdateOne) SetWidth(v int) *ImageUpdateOne {
	_u.mutation.ResetWidth()
	_u.mutation.SetWidth(v)
	return _u
}

// SetNillableWidth sets the "width" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableWidth(v *int) *ImageUpdateOne {
	if v != nil {
		_u.SetWidth(*v)
	}
	return _u
}

// AddWidth adds value to the "width" field.
func (_u *ImageUpdateOne) AddWidth(v int) *ImageUpdateOne {
	_u.mutation.AddWidth(v)
	return _u
}

// SetHeight sets the "height" field.
func (_u *ImageUpdateOne) SetHeight(v int) *ImageUpdateOne {
	_u.mutation.ResetHeight()
	_u.mutation.SetHeight(v)
	return _u
}

// SetNillableHeight sets the "height" field if the given value is not nil.
func (_u *ImageUpdateOne) SetNillableHeight(v *int) *ImageUpdateOne {
	if v != nil {
		_u.SetHeight(*v)
	}
	return _u
}

// AddHeight adds value to the "height" field.
func (_u *ImageUpdateOne) AddHeight(v int) *ImageUpdateOne {
	_u.mutation.AddHeight(v)
	return _u
}

// SetGameID sets the "game" edge to the Game entity by ID.
func (_u *ImageUpdateOne) SetGameID(id string) *ImageUpdateOne {
	_u.mutation.SetGameID(id)
	return _u
}

// SetGame sets the "game" edge to the Game entity.
func (_u *ImageUpdateOne) SetGame(v *Game) *ImageUpdateOne {
	return _u.SetGameID(v.ID)
}

// Mutation returns the ImageMutation object of the builder.
func (_u *ImageUpdateOne) Mutation() *ImageMutation {
	return _u.mutation
}

// ClearGame clears the "game" edge to the Game entity.
func (_u *ImageUpdateOne) ClearGame() *ImageUpdateOne {
	_u.mutation.ClearGame()
	return _u
}

// Where appends a list predicates to the ImageUpdate builder.
func (_u *ImageUpdateOne) Where(ps ...predicate.Image) *ImageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ImageUpdateOne) Select(field string, fields ...string) *ImageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Image entity.
func (_u *ImageUpdateOne) Save(ctx context.Context) (*Image, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ImageUpdateOne) SaveX(ctx context.Context) *Image {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ImageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ImageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ImageUpdateOne) check() error {
	if v, ok := _u.mutation.Kind(); ok {
		if err := image.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Image.kind": %w`, err)}
		}
	}
	if _u.mutation.GameCleared() && len(_u.mutation.GameIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Image.game"`)
	}
	return nil
}

func (_u *ImageUpdateOne) sqlSave(ctx context.Context) (_node *Image, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(image.Table, image.Columns, sqlgraph.NewFieldSpec(image.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Image.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, image.FieldID)
		for _, f := range fields {
			if !image.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != image.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(image.FieldKind, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(image.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.S3Key(); ok {
		_spec.SetField(image.FieldS3Key, field.TypeString, value)
	}
	if value, ok := _u.mutation.Width(); ok {
		_spec.SetField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWidth(); ok {
		_spec.AddField(image.FieldWidth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Height(); ok {
		_spec.SetField(image.FieldHeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHeight(); ok {
		_spec.AddField(image.FieldHeight, field.TypeInt, value)
	}
	if _u.mutation.GameCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GameIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   image.GameTable,
			Columns: []string{image.GameColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(game.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Image{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{image.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
