// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/predicate"
	"github.com/deicod/archivedgames/ent/report"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (ru *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	ru.mutation.Where(ps...)
	return ru
}

// SetSubjectType sets the "subject_type" field.
func (ru *ReportUpdate) SetSubjectType(s string) *ReportUpdate {
	ru.mutation.SetSubjectType(s)
	return ru
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableSubjectType(s *string) *ReportUpdate {
	if s != nil {
		ru.SetSubjectType(*s)
	}
	return ru
}

// SetSubjectXid sets the "subject_xid" field.
func (ru *ReportUpdate) SetSubjectXid(s string) *ReportUpdate {
	ru.mutation.SetSubjectXid(s)
	return ru
}

// SetNillableSubjectXid sets the "subject_xid" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableSubjectXid(s *string) *ReportUpdate {
	if s != nil {
		ru.SetSubjectXid(*s)
	}
	return ru
}

// SetReporterID sets the "reporter_id" field.
func (ru *ReportUpdate) SetReporterID(s string) *ReportUpdate {
	ru.mutation.SetReporterID(s)
	return ru
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReporterID(s *string) *ReportUpdate {
	if s != nil {
		ru.SetReporterID(*s)
	}
	return ru
}

// ClearReporterID clears the value of the "reporter_id" field.
func (ru *ReportUpdate) ClearReporterID() *ReportUpdate {
	ru.mutation.ClearReporterID()
	return ru
}

// SetReason sets the "reason" field.
func (ru *ReportUpdate) SetReason(s string) *ReportUpdate {
	ru.mutation.SetReason(s)
	return ru
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableReason(s *string) *ReportUpdate {
	if s != nil {
		ru.SetReason(*s)
	}
	return ru
}

// SetNote sets the "note" field.
func (ru *ReportUpdate) SetNote(s string) *ReportUpdate {
	ru.mutation.SetNote(s)
	return ru
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableNote(s *string) *ReportUpdate {
	if s != nil {
		ru.SetNote(*s)
	}
	return ru
}

// ClearNote clears the value of the "note" field.
func (ru *ReportUpdate) ClearNote() *ReportUpdate {
	ru.mutation.ClearNote()
	return ru
}

// SetStatus sets the "status" field.
func (ru *ReportUpdate) SetStatus(r report.Status) *ReportUpdate {
	ru.mutation.SetStatus(r)
	return ru
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ru *ReportUpdate) SetNillableStatus(r *report.Status) *ReportUpdate {
	if r != nil {
		ru.SetStatus(*r)
	}
	return ru
}

// Mutation returns the ReportMutation object of the builder.
func (ru *ReportUpdate) Mutation() *ReportMutation {
	return ru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ru *ReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ru.sqlSave, ru.mutation, ru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ru *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := ru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ru *ReportUpdate) Exec(ctx context.Context) error {
	_, err := ru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ru *ReportUpdate) ExecX(ctx context.Context) {
	if err := ru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ru *ReportUpdate) check() error {
	if v, ok := ru.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	return nil
}

func (ru *ReportUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	if ps := ru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ru.mutation.SubjectType(); ok {
		_spec.SetField(report.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := ru.mutation.SubjectXid(); ok {
		_spec.SetField(report.FieldSubjectXid, field.TypeString, value)
	}
	if value, ok := ru.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeString, value)
	}
	if ru.mutation.ReporterIDCleared() {
		_spec.ClearField(report.FieldReporterID, field.TypeString)
	}
	if value, ok := ru.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
	}
	if value, ok := ru.mutation.Note(); ok {
		_spec.SetField(report.FieldNote, field.TypeString, value)
	}
	if ru.mutation.NoteCleared() {
		_spec.ClearField(report.FieldNote, field.TypeString)
	}
	if value, ok := ru.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ru.mutation.done = true
	return n, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetSubjectType sets the "subject_type" field.
func (ruo *ReportUpdateOne) SetSubjectType(s string) *ReportUpdateOne {
	ruo.mutation.SetSubjectType(s)
	return ruo
}

// SetNillableSubjectType sets the "subject_type" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableSubjectType(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetSubjectType(*s)
	}
	return ruo
}

// SetSubjectXid sets the "subject_xid" field.
func (ruo *ReportUpdateOne) SetSubjectXid(s string) *ReportUpdateOne {
	ruo.mutation.SetSubjectXid(s)
	return ruo
}

// SetNillableSubjectXid sets the "subject_xid" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableSubjectXid(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetSubjectXid(*s)
	}
	return ruo
}

// SetReporterID sets the "reporter_id" field.
func (ruo *ReportUpdateOne) SetReporterID(s string) *ReportUpdateOne {
	ruo.mutation.SetReporterID(s)
	return ruo
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReporterID(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetReporterID(*s)
	}
	return ruo
}

// ClearReporterID clears the value of the "reporter_id" field.
func (ruo *ReportUpdateOne) ClearReporterID() *ReportUpdateOne {
	ruo.mutation.ClearReporterID()
	return ruo
}

// SetReason sets the "reason" field.
func (ruo *ReportUpdateOne) SetReason(s string) *ReportUpdateOne {
	ruo.mutation.SetReason(s)
	return ruo
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableReason(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetReason(*s)
	}
	return ruo
}

// SetNote sets the "note" field.
func (ruo *ReportUpdateOne) SetNote(s string) *ReportUpdateOne {
	ruo.mutation.SetNote(s)
	return ruo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableNote(s *string) *ReportUpdateOne {
	if s != nil {
		ruo.SetNote(*s)
	}
	return ruo
}

// ClearNote clears the value of the "note" field.
func (ruo *ReportUpdateOne) ClearNote() *ReportUpdateOne {
	ruo.mutation.ClearNote()
	return ruo
}

// SetStatus sets the "status" field.
func (ruo *ReportUpdateOne) SetStatus(r report.Status) *ReportUpdateOne {
	ruo.mutation.SetStatus(r)
	return ruo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ruo *ReportUpdateOne) SetNillableStatus(r *report.Status) *ReportUpdateOne {
	if r != nil {
		ruo.SetStatus(*r)
	}
	return ruo
}

// Mutation returns the ReportMutation object of the builder.
func (ruo *ReportUpdateOne) Mutation() *ReportMutation {
	return ruo.mutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (ruo *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	ruo.mutation.Where(ps...)
	return ruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ruo *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	ruo.fields = append([]string{field}, fields...)
	return ruo
}

// Save executes the query and returns the updated Report entity.
func (ruo *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	return withHooks(ctx, ruo.sqlSave, ruo.mutation, ruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ruo *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := ruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ruo *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := ruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ruo *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := ruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ruo *ReportUpdateOne) check() error {
	if v, ok := ruo.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	return nil
}

func (ruo *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	if err := ruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	id, ok := ruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ruo.mutation.SubjectType(); ok {
		_spec.SetField(report.FieldSubjectType, field.TypeString, value)
	}
	if value, ok := ruo.mutation.SubjectXid(); ok {
		_spec.SetField(report.FieldSubjectXid, field.TypeString, value)
	}
	if value, ok := ruo.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeString, value)
	}
	if ruo.mutation.ReporterIDCleared() {
		_spec.ClearField(report.FieldReporterID, field.TypeString)
	}
	if value, ok := ruo.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
	}
	if value, ok := ruo.mutation.Note(); ok {
		_spec.SetField(report.FieldNote, field.TypeString, value)
	}
	if ruo.mutation.NoteCleared() {
		_spec.ClearField(report.FieldNote, field.TypeString)
	}
	if value, ok := ruo.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
	}
	_node = &Report{config: ruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ruo.mutation.done = true
	return _node, nil
}
