// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/report"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
}

// SetSubjectType sets the "subject_type" field.
func (rc *ReportCreate) SetSubjectType(s string) *ReportCreate {
	rc.mutation.SetSubjectType(s)
	return rc
}

// SetSubjectXid sets the "subject_xid" field.
func (rc *ReportCreate) SetSubjectXid(s string) *ReportCreate {
	rc.mutation.SetSubjectXid(s)
	return rc
}

// SetReporterID sets the "reporter_id" field.
func (rc *ReportCreate) SetReporterID(s string) *ReportCreate {
	rc.mutation.SetReporterID(s)
	return rc
}

// SetNillableReporterID sets the "reporter_id" field if the given value is not nil.
func (rc *ReportCreate) SetNillableReporterID(s *string) *ReportCreate {
	if s != nil {
		rc.SetReporterID(*s)
	}
	return rc
}

// SetReason sets the "reason" field.
func (rc *ReportCreate) SetReason(s string) *ReportCreate {
	rc.mutation.SetReason(s)
	return rc
}

// SetNote sets the "note" field.
func (rc *ReportCreate) SetNote(s string) *ReportCreate {
	rc.mutation.SetNote(s)
	return rc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (rc *ReportCreate) SetNillableNote(s *string) *ReportCreate {
	if s != nil {
		rc.SetNote(*s)
	}
	return rc
}

// SetStatus sets the "status" field.
func (rc *ReportCreate) SetStatus(r report.Status) *ReportCreate {
	rc.mutation.SetStatus(r)
	return rc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (rc *ReportCreate) SetNillableStatus(r *report.Status) *ReportCreate {
	if r != nil {
		rc.SetStatus(*r)
	}
	return rc
}

// Mutation returns the ReportMutation object of the builder.
func (rc *ReportCreate) Mutation() *ReportMutation {
	return rc.mutation
}

// Save creates the Report in the database.
func (rc *ReportCreate) Save(ctx context.Context) (*Report, error) {
	rc.defaults()
	return withHooks(ctx, rc.sqlSave, rc.mutation, rc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rc *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := rc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rc *ReportCreate) Exec(ctx context.Context) error {
	_, err := rc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rc *ReportCreate) ExecX(ctx context.Context) {
	if err := rc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rc *ReportCreate) defaults() {
	if _, ok := rc.mutation.Status(); !ok {
		v := report.DefaultStatus
		rc.mutation.SetStatus(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rc *ReportCreate) check() error {
	if _, ok := rc.mutation.SubjectType(); !ok {
		return &ValidationError{Name: "subject_type", err: errors.New(`ent: missing required field "Report.subject_type"`)}
	}
	if _, ok := rc.mutation.SubjectXid(); !ok {
		return &ValidationError{Name: "subject_xid", err: errors.New(`ent: missing required field "Report.subject_xid"`)}
	}
	if _, ok := rc.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "Report.reason"`)}
	}
	if _, ok := rc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Report.status"`)}
	}
	if v, ok := rc.mutation.Status(); ok {
		if err := report.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Report.status": %w`, err)}
		}
	}
	return nil
}

func (rc *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := rc.check(); err != nil {
		return nil, err
	}
	_node, _spec := rc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	rc.mutation.id = &_node.ID
	rc.mutation.done = true
	return _node, nil
}

func (rc *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: rc.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeInt))
	)
	if value, ok := rc.mutation.SubjectType(); ok {
		_spec.SetField(report.FieldSubjectType, field.TypeString, value)
		_node.SubjectType = value
	}
	if value, ok := rc.mutation.SubjectXid(); ok {
		_spec.SetField(report.FieldSubjectXid, field.TypeString, value)
		_node.SubjectXid = value
	}
	if value, ok := rc.mutation.ReporterID(); ok {
		_spec.SetField(report.FieldReporterID, field.TypeString, value)
		_node.ReporterID = value
	}
	if value, ok := rc.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := rc.mutation.Note(); ok {
		_spec.SetField(report.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := rc.mutation.Status(); ok {
		_spec.SetField(report.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	return _node, _spec
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
}

// Save creates the Report entities in the database.
func (rcb *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if rcb.err != nil {
		return nil, rcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(rcb.builders))
	nodes := make([]*Report, len(rcb.builders))
	mutators := make([]Mutator, len(rcb.builders))
	for i := range rcb.builders {
		func(i int, root context.Context) {
			builder := rcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, rcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, rcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, rcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (rcb *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := rcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rcb *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := rcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rcb *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := rcb.Exec(ctx); err != nil {
		panic(err)
	}
}
