// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/deicod/archivedgames/ent/file"
	"github.com/deicod/archivedgames/ent/game"
	"github.com/deicod/archivedgames/ent/image"
	"github.com/deicod/archivedgames/ent/schema"
	"github.com/deicod/archivedgames/ent/sitesetting"
	"github.com/deicod/archivedgames/ent/usershadow"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescXid is the schema descriptor for xid field.
	fileDescXid := fileFields[0].Descriptor()
	// file.DefaultXid holds the default value on creation for the xid field.
	file.DefaultXid = fileDescXid.Default.(func() string)
	// fileDescQuarantine is the schema descriptor for quarantine field.
	fileDescQuarantine := fileFields[9].Descriptor()
	// file.DefaultQuarantine holds the default value on creation for the quarantine field.
	file.DefaultQuarantine = fileDescQuarantine.Default.(bool)
	// fileDescNeedsReview is the schema descriptor for needs_review field.
	fileDescNeedsReview := fileFields[10].Descriptor()
	// file.DefaultNeedsReview holds the default value on creation for the needs_review field.
	file.DefaultNeedsReview = fileDescNeedsReview.Default.(bool)
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescXid is the schema descriptor for xid field.
	gameDescXid := gameFields[0].Descriptor()
	// game.DefaultXid holds the default value on creation for the xid field.
	game.DefaultXid = gameDescXid.Default.(func() string)
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescXid is the schema descriptor for xid field.
	imageDescXid := imageFields[0].Descriptor()
	// image.DefaultXid holds the default value on creation for the xid field.
	image.DefaultXid = imageDescXid.Default.(func() string)
	// imageDescPosition is the schema descriptor for position field.
	imageDescPosition := imageFields[2].Descriptor()
	// image.DefaultPosition holds the default value on creation for the position field.
	image.DefaultPosition = imageDescPosition.Default.(int)
	sitesettingFields := schema.SiteSetting{}.Fields()
	_ = sitesettingFields
	// sitesettingDescPublic is the schema descriptor for public field.
	sitesettingDescPublic := sitesettingFields[2].Descriptor()
	// sitesetting.DefaultPublic holds the default value on creation for the public field.
	sitesetting.DefaultPublic = sitesettingDescPublic.Default.(bool)
	usershadowFields := schema.UserShadow{}.Fields()
	_ = usershadowFields
	// usershadowDescXid is the schema descriptor for xid field.
	usershadowDescXid := usershadowFields[0].Descriptor()
	// usershadow.DefaultXid holds the default value on creation for the xid field.
	usershadow.DefaultXid = usershadowDescXid.Default.(func() string)
}
