// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/deicod/archivedgames/ent/comment"
	"github.com/deicod/archivedgames/ent/file"
	"github.com/deicod/archivedgames/ent/filegroup"
	"github.com/deicod/archivedgames/ent/filereaction"
	"github.com/deicod/archivedgames/ent/game"
	"github.com/deicod/archivedgames/ent/gamelike"
	"github.com/deicod/archivedgames/ent/image"
	"github.com/deicod/archivedgames/ent/report"
	"github.com/deicod/archivedgames/ent/schema"
	"github.com/deicod/archivedgames/ent/sitesetting"
	"github.com/deicod/archivedgames/ent/usershadow"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[6].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescID is the schema descriptor for id field.
	commentDescID := commentFields[0].Descriptor()
	// comment.DefaultID holds the default value on creation for the id field.
	comment.DefaultID = commentDescID.Default.(func() string)
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescQuarantine is the schema descriptor for quarantine field.
	fileDescQuarantine := fileFields[10].Descriptor()
	// file.DefaultQuarantine holds the default value on creation for the quarantine field.
	file.DefaultQuarantine = fileDescQuarantine.Default.(bool)
	// fileDescNeedsReview is the schema descriptor for needs_review field.
	fileDescNeedsReview := fileFields[11].Descriptor()
	// file.DefaultNeedsReview holds the default value on creation for the needs_review field.
	file.DefaultNeedsReview = fileDescNeedsReview.Default.(bool)
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileFields[0].Descriptor()
	// file.DefaultID holds the default value on creation for the id field.
	file.DefaultID = fileDescID.Default.(func() string)
	filegroupFields := schema.FileGroup{}.Fields()
	_ = filegroupFields
	// filegroupDescID is the schema descriptor for id field.
	filegroupDescID := filegroupFields[0].Descriptor()
	// filegroup.DefaultID holds the default value on creation for the id field.
	filegroup.DefaultID = filegroupDescID.Default.(func() string)
	filereactionFields := schema.FileReaction{}.Fields()
	_ = filereactionFields
	// filereactionDescID is the schema descriptor for id field.
	filereactionDescID := filereactionFields[0].Descriptor()
	// filereaction.DefaultID holds the default value on creation for the id field.
	filereaction.DefaultID = filereactionDescID.Default.(func() string)
	gameFields := schema.Game{}.Fields()
	_ = gameFields
	// gameDescID is the schema descriptor for id field.
	gameDescID := gameFields[0].Descriptor()
	// game.DefaultID holds the default value on creation for the id field.
	game.DefaultID = gameDescID.Default.(func() string)
	gamelikeFields := schema.GameLike{}.Fields()
	_ = gamelikeFields
	// gamelikeDescID is the schema descriptor for id field.
	gamelikeDescID := gamelikeFields[0].Descriptor()
	// gamelike.DefaultID holds the default value on creation for the id field.
	gamelike.DefaultID = gamelikeDescID.Default.(func() string)
	imageFields := schema.Image{}.Fields()
	_ = imageFields
	// imageDescPosition is the schema descriptor for position field.
	imageDescPosition := imageFields[2].Descriptor()
	// image.DefaultPosition holds the default value on creation for the position field.
	image.DefaultPosition = imageDescPosition.Default.(int)
	// imageDescID is the schema descriptor for id field.
	imageDescID := imageFields[0].Descriptor()
	// image.DefaultID holds the default value on creation for the id field.
	image.DefaultID = imageDescID.Default.(func() string)
	reportFields := schema.Report{}.Fields()
	_ = reportFields
	// reportDescID is the schema descriptor for id field.
	reportDescID := reportFields[0].Descriptor()
	// report.DefaultID holds the default value on creation for the id field.
	report.DefaultID = reportDescID.Default.(func() string)
	sitesettingFields := schema.SiteSetting{}.Fields()
	_ = sitesettingFields
	// sitesettingDescPublic is the schema descriptor for public field.
	sitesettingDescPublic := sitesettingFields[3].Descriptor()
	// sitesetting.DefaultPublic holds the default value on creation for the public field.
	sitesetting.DefaultPublic = sitesettingDescPublic.Default.(bool)
	// sitesettingDescID is the schema descriptor for id field.
	sitesettingDescID := sitesettingFields[0].Descriptor()
	// sitesetting.DefaultID holds the default value on creation for the id field.
	sitesetting.DefaultID = sitesettingDescID.Default.(func() string)
	usershadowFields := schema.UserShadow{}.Fields()
	_ = usershadowFields
	// usershadowDescID is the schema descriptor for id field.
	usershadowDescID := usershadowFields[0].Descriptor()
	// usershadow.DefaultID holds the default value on creation for the id field.
	usershadow.DefaultID = usershadowDescID.Default.(func() string)
}
