// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/deicod/archivedgames/ent/predicate"
	"github.com/deicod/archivedgames/ent/usershadow"
)

// UserShadowUpdate is the builder for updating UserShadow entities.
type UserShadowUpdate struct {
	config
	hooks    []Hook
	mutation *UserShadowMutation
}

// Where appends a list predicates to the UserShadowUpdate builder.
func (usu *UserShadowUpdate) Where(ps ...predicate.UserShadow) *UserShadowUpdate {
	usu.mutation.Where(ps...)
	return usu
}

// SetKeycloakSub sets the "keycloak_sub" field.
func (usu *UserShadowUpdate) SetKeycloakSub(s string) *UserShadowUpdate {
	usu.mutation.SetKeycloakSub(s)
	return usu
}

// SetNillableKeycloakSub sets the "keycloak_sub" field if the given value is not nil.
func (usu *UserShadowUpdate) SetNillableKeycloakSub(s *string) *UserShadowUpdate {
	if s != nil {
		usu.SetKeycloakSub(*s)
	}
	return usu
}

// SetHandle sets the "handle" field.
func (usu *UserShadowUpdate) SetHandle(s string) *UserShadowUpdate {
	usu.mutation.SetHandle(s)
	return usu
}

// SetNillableHandle sets the "handle" field if the given value is not nil.
func (usu *UserShadowUpdate) SetNillableHandle(s *string) *UserShadowUpdate {
	if s != nil {
		usu.SetHandle(*s)
	}
	return usu
}

// ClearHandle clears the value of the "handle" field.
func (usu *UserShadowUpdate) ClearHandle() *UserShadowUpdate {
	usu.mutation.ClearHandle()
	return usu
}

// SetDisplayName sets the "display_name" field.
func (usu *UserShadowUpdate) SetDisplayName(s string) *UserShadowUpdate {
	usu.mutation.SetDisplayName(s)
	return usu
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (usu *UserShadowUpdate) SetNillableDisplayName(s *string) *UserShadowUpdate {
	if s != nil {
		usu.SetDisplayName(*s)
	}
	return usu
}

// ClearDisplayName clears the value of the "display_name" field.
func (usu *UserShadowUpdate) ClearDisplayName() *UserShadowUpdate {
	usu.mutation.ClearDisplayName()
	return usu
}

// Mutation returns the UserShadowMutation object of the builder.
func (usu *UserShadowUpdate) Mutation() *UserShadowMutation {
	return usu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (usu *UserShadowUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, usu.sqlSave, usu.mutation, usu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usu *UserShadowUpdate) SaveX(ctx context.Context) int {
	affected, err := usu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (usu *UserShadowUpdate) Exec(ctx context.Context) error {
	_, err := usu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usu *UserShadowUpdate) ExecX(ctx context.Context) {
	if err := usu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usu *UserShadowUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(usershadow.Table, usershadow.Columns, sqlgraph.NewFieldSpec(usershadow.FieldID, field.TypeString))
	if ps := usu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usu.mutation.KeycloakSub(); ok {
		_spec.SetField(usershadow.FieldKeycloakSub, field.TypeString, value)
	}
	if value, ok := usu.mutation.Handle(); ok {
		_spec.SetField(usershadow.FieldHandle, field.TypeString, value)
	}
	if usu.mutation.HandleCleared() {
		_spec.ClearField(usershadow.FieldHandle, field.TypeString)
	}
	if value, ok := usu.mutation.DisplayName(); ok {
		_spec.SetField(usershadow.FieldDisplayName, field.TypeString, value)
	}
	if usu.mutation.DisplayNameCleared() {
		_spec.ClearField(usershadow.FieldDisplayName, field.TypeString)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, usu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usershadow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	usu.mutation.done = true
	return n, nil
}

// UserShadowUpdateOne is the builder for updating a single UserShadow entity.
type UserShadowUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserShadowMutation
}

// SetKeycloakSub sets the "keycloak_sub" field.
func (usuo *UserShadowUpdateOne) SetKeycloakSub(s string) *UserShadowUpdateOne {
	usuo.mutation.SetKeycloakSub(s)
	return usuo
}

// SetNillableKeycloakSub sets the "keycloak_sub" field if the given value is not nil.
func (usuo *UserShadowUpdateOne) SetNillableKeycloakSub(s *string) *UserShadowUpdateOne {
	if s != nil {
		usuo.SetKeycloakSub(*s)
	}
	return usuo
}

// SetHandle sets the "handle" field.
func (usuo *UserShadowUpdateOne) SetHandle(s string) *UserShadowUpdateOne {
	usuo.mutation.SetHandle(s)
	return usuo
}

// SetNillableHandle sets the "handle" field if the given value is not nil.
func (usuo *UserShadowUpdateOne) SetNillableHandle(s *string) *UserShadowUpdateOne {
	if s != nil {
		usuo.SetHandle(*s)
	}
	return usuo
}

// ClearHandle clears the value of the "handle" field.
func (usuo *UserShadowUpdateOne) ClearHandle() *UserShadowUpdateOne {
	usuo.mutation.ClearHandle()
	return usuo
}

// SetDisplayName sets the "display_name" field.
func (usuo *UserShadowUpdateOne) SetDisplayName(s string) *UserShadowUpdateOne {
	usuo.mutation.SetDisplayName(s)
	return usuo
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (usuo *UserShadowUpdateOne) SetNillableDisplayName(s *string) *UserShadowUpdateOne {
	if s != nil {
		usuo.SetDisplayName(*s)
	}
	return usuo
}

// ClearDisplayName clears the value of the "display_name" field.
func (usuo *UserShadowUpdateOne) ClearDisplayName() *UserShadowUpdateOne {
	usuo.mutation.ClearDisplayName()
	return usuo
}

// Mutation returns the UserShadowMutation object of the builder.
func (usuo *UserShadowUpdateOne) Mutation() *UserShadowMutation {
	return usuo.mutation
}

// Where appends a list predicates to the UserShadowUpdate builder.
func (usuo *UserShadowUpdateOne) Where(ps ...predicate.UserShadow) *UserShadowUpdateOne {
	usuo.mutation.Where(ps...)
	return usuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (usuo *UserShadowUpdateOne) Select(field string, fields ...string) *UserShadowUpdateOne {
	usuo.fields = append([]string{field}, fields...)
	return usuo
}

// Save executes the query and returns the updated UserShadow entity.
func (usuo *UserShadowUpdateOne) Save(ctx context.Context) (*UserShadow, error) {
	return withHooks(ctx, usuo.sqlSave, usuo.mutation, usuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (usuo *UserShadowUpdateOne) SaveX(ctx context.Context) *UserShadow {
	node, err := usuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (usuo *UserShadowUpdateOne) Exec(ctx context.Context) error {
	_, err := usuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (usuo *UserShadowUpdateOne) ExecX(ctx context.Context) {
	if err := usuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (usuo *UserShadowUpdateOne) sqlSave(ctx context.Context) (_node *UserShadow, err error) {
	_spec := sqlgraph.NewUpdateSpec(usershadow.Table, usershadow.Columns, sqlgraph.NewFieldSpec(usershadow.FieldID, field.TypeString))
	id, ok := usuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserShadow.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := usuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usershadow.FieldID)
		for _, f := range fields {
			if !usershadow.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usershadow.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := usuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := usuo.mutation.KeycloakSub(); ok {
		_spec.SetField(usershadow.FieldKeycloakSub, field.TypeString, value)
	}
	if value, ok := usuo.mutation.Handle(); ok {
		_spec.SetField(usershadow.FieldHandle, field.TypeString, value)
	}
	if usuo.mutation.HandleCleared() {
		_spec.ClearField(usershadow.FieldHandle, field.TypeString)
	}
	if value, ok := usuo.mutation.DisplayName(); ok {
		_spec.SetField(usershadow.FieldDisplayName, field.TypeString, value)
	}
	if usuo.mutation.DisplayNameCleared() {
		_spec.ClearField(usershadow.FieldDisplayName, field.TypeString)
	}
	_node = &UserShadow{config: usuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, usuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usershadow.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	usuo.mutation.done = true
	return _node, nil
}
